name: CI Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Install Python dependencies
        run: |
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
          python -m pip install pytest

      - name: Run tests (pytest)
        run: |
          set -e
          pytest -q

      - name: Upload test results (junit)
        if: always()
        run: |
          python -m pip install pytest junitxml
          pytest --junitxml=results.xml || true
        # upload artifact so failures are retained
      - name: Upload results artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: results.xml

