name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint (ruff + flake8)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          pip install ruff flake8
      - name: Run ruff
        run: ruff check .
      - name: Run flake8
        run: flake8 .

  test:
    name: Test & Coverage
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        python-version: [3.11]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov
      - name: Run tests with coverage
        run: |
          pytest --maxfail=1 -q --disable-warnings --cov=report --cov-report=xml:coverage.xml --cov-report=html:htmlcov --cov-fail-under=80
      - name: Upload coverage HTML artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: htmlcov
      - name: Upload coverage XML to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
          fail_ci_if_error: true

  publish_demo:
    name: Publish demo_report_multi.html to gh-pages
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Render demo report
        run: python demo_render.py
      - name: Prepare public directory
        run: |
          mkdir -p public
          cp demo_report_multi.html public/index.html
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
